import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2, GraduationCap, Home, MapPin, ShoppingBag, Trophy, Trees } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { CommunityBreadcrumb } from "@/components/seo/CommunityBreadcrumb";

const siteUrl = "https://azheartsinhomes.com";

export const metadata: Metadata = {
  title: "Glendale AZ Realtor | Glendale Real Estate & Homes for Sale",
  description: "Looking for a Glendale AZ Realtor? Explore Glendale neighborhoods, homes, shopping, sports, entertainment, education and recreation with REALTOR® Darek Dowsett.",
  alternates: { canonical: "/communities/glendale" },
  openGraph: { title: "Glendale AZ Realtor | Glendale Real Estate & Homes for Sale", description: "Explore Glendale real estate, neighborhoods, shopping, entertainment, education and recreation with REALTOR® Darek Dowsett.", url: `${siteUrl}/communities/glendale`, type: "website" },
};

const areas = [
  { title: "Arrowhead Ranch", text: "An established Northwest Valley area with neighborhoods, golf, shopping, dining, parks and convenient access to Loop 101." },
  { title: "Westgate & Sports District", text: "A major entertainment and sports destination surrounded by restaurants, shopping, concerts, events and nearby housing." },
  { title: "North Glendale", text: "A mix of established and newer neighborhoods with access to shopping, recreation, schools and the broader Northwest Valley." },
  { title: "Historic Downtown Glendale", text: "Known for historic character, locally owned businesses, antique shopping, restaurants and seasonal community events." },
];

const faqs = [
  { question: "Is Glendale AZ a good place to buy a home?", answer: "Glendale offers established neighborhoods, newer communities, shopping, recreation, entertainment, education and a wide range of housing options. The right fit depends on your budget, preferred lifestyle, commute and long-term plans." },
  { question: "What shopping is available in Glendale?", answer: "Glendale offers major shopping destinations including Arrowhead Towne Center, Tanger Phoenix, Westgate Entertainment District and historic downtown Glendale, along with many local shops and restaurants." },
  { question: "What colleges are in Glendale?", answer: "Glendale Community College has its main campus at 6000 W. Olive Ave. in Glendale and also operates GCC North in northwest Phoenix. ASU's West Valley campus is at 4701 W. Thunderbird Road in Glendale and offers more than 125 undergraduate and graduate degree programs." },
  { question: "What entertainment and amusement attractions are in Glendale?", answer: "Glendale's entertainment options include Westgate Entertainment District, Desert Diamond Arena, Andretti Indoor Karting & Games, Topgolf, Desert Diamond Casino and the planned Mattel Adventure Park. Mattel Adventure Park is an evolving development, so opening details should be checked before planning a visit." },
  { question: "Can you help me sell a home in Glendale?", answer: "Yes. I provide full-service representation including pricing strategy, marketing, negotiations, transaction management, inspections, closing and follow-up after the transaction." },
];

const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    { "@type": "WebPage", "@id": `${siteUrl}/communities/glendale#webpage`, url: `${siteUrl}/communities/glendale`, name: "Glendale AZ Realtor | Glendale Real Estate & Homes for Sale", description: "Explore Glendale real estate, neighborhoods, shopping, entertainment, education and recreation with REALTOR® Darek Dowsett.", isPartOf: { "@id": `${siteUrl}/#website` }, about: { "@type": "City", name: "Glendale", address: { "@type": "PostalAddress", addressRegion: "AZ", addressCountry: "US" } } },
    { "@type": "FAQPage", mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) },
  ],
};

export default function GlendalePage() {
  return (
    <main className="bg-background">
      <CommunityBreadcrumb name="Glendale" slug="glendale" />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />

      <section className="relative overflow-hidden"><div className="pointer-events-none absolute inset-0" aria-hidden="true"><div className="absolute -left-40 top-20 h-[30rem] w-[30rem] rounded-full bg-amber-100/40 blur-3xl" /><div className="absolute bottom-0 right-0 h-[30rem] w-[30rem] rounded-full bg-orange-100/30 blur-3xl" /></div><div className="relative mx-auto max-w-7xl px-6 py-24"><div className="mx-auto max-w-4xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.35em] text-orange-500">GLENDALE, ARIZONA</p><h1 className="mt-6 text-5xl font-bold leading-tight md:text-6xl">Glendale AZ Real Estate &amp; Homes for Sale</h1><p className="mt-8 text-xl leading-9 text-muted-foreground">Glendale combines established neighborhoods with a major sports and entertainment district, extensive shopping, higher education, community colleges, recreation and a wide variety of homes.</p><div className="mt-10 flex flex-wrap justify-center gap-4"><Link href="/buyers"><Button size="lg" className="px-8">Search Glendale Homes</Button></Link><Link href="/contact"><Button size="lg" variant="outline" className="px-8">Talk With Me</Button></Link></div></div></div></section>

      <section className="bg-stone-50 py-24"><div className="mx-auto max-w-6xl px-6"><div className="grid gap-8 md:grid-cols-4">{[
        { icon: Trophy, title: "Sports & Events", text: "State Farm Stadium, Desert Diamond Arena, Spring Training and major events make Glendale a destination for sports and entertainment." },
        { icon: ShoppingBag, title: "Shopping", text: "Arrowhead Towne Center, Tanger Phoenix, Westgate and Historic Downtown Glendale give residents many shopping choices." },
        { icon: Trees, title: "Recreation", text: "Parks, golf, community facilities and nearby outdoor destinations provide plenty of ways to enjoy the West Valley." },
        { icon: GraduationCap, title: "Education", text: "Glendale Community College and ASU's West Valley campus provide higher-education options within Glendale." },
      ].map((item) => <Card key={item.title} className="rounded-3xl"><CardContent className="p-8 text-center"><item.icon className="mx-auto h-12 w-12 text-orange-500" /><h2 className="mt-6 text-2xl font-bold">{item.title}</h2><p className="mt-4 leading-8 text-muted-foreground">{item.text}</p></CardContent></Card>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-6 py-24"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.35em] text-orange-500">GLENDALE NEIGHBORHOODS</p><h2 className="mt-4 text-4xl font-bold md:text-5xl">Which Part of Glendale Fits You?</h2><p className="mt-8 text-lg leading-8 text-muted-foreground">Glendale encompasses very different neighborhoods and lifestyles. Understanding the location can be just as important as choosing the house.</p></div><div className="mt-16 grid gap-8 md:grid-cols-2">{areas.map((area) => <Card key={area.title} className="rounded-3xl"><CardContent className="p-8"><div className="flex items-start gap-5"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-orange-50"><MapPin className="h-6 w-6 text-orange-500" /></div><div><h3 className="text-2xl font-bold">{area.title}</h3><p className="mt-4 leading-8 text-muted-foreground">{area.text}</p></div></div></CardContent></Card>)}</div></section>

      <section className="bg-orange-50 py-24"><div className="mx-auto max-w-6xl px-6"><div className="grid gap-14 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.35em] text-orange-500">SHOPPING &amp; ENTERTAINMENT</p><h2 className="mt-4 text-4xl font-bold md:text-5xl">A Lot To Do Without Leaving Glendale</h2><p className="mt-7 text-lg leading-8 text-muted-foreground">Glendale's Westgate Entertainment District combines restaurants, retail, nightlife, concerts and events. Nearby Tanger Phoenix provides open-air outlet shopping, while Arrowhead Towne Center adds another major retail destination.</p><p className="mt-6 text-lg leading-8 text-muted-foreground">For families and entertainment seekers, Glendale also offers Andretti Indoor Karting &amp; Games, Topgolf and other attractions. Desert Diamond Arena hosts major concerts and events.</p></div><div className="space-y-5">{["Westgate Entertainment District","Tanger Phoenix outlet shopping","Arrowhead Towne Center","Desert Diamond Arena concerts and events","Andretti Indoor Karting & Games","Topgolf and family entertainment"].map((item) => <div key={item} className="flex items-center gap-4"><CheckCircle2 className="h-6 w-6 shrink-0 text-orange-500" /><span className="text-lg">{item}</span></div>)}</div></div></div></section>

      <section className="mx-auto max-w-7xl px-6 py-24"><div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[0.35em] text-orange-500">EDUCATION &amp; GLENDALE</p><h2 className="mt-4 text-4xl font-bold md:text-5xl">College Options Are Part Of The Local Lifestyle</h2><p className="mt-8 text-lg leading-8 text-muted-foreground">For families, students and education-focused buyers, Glendale has the advantage of having both a community college and a major university campus nearby.</p></div><div className="mt-12 grid gap-8 md:grid-cols-2"><Card className="rounded-3xl"><CardContent className="p-8"><GraduationCap className="h-12 w-12 text-orange-500" /><h3 className="mt-6 text-2xl font-bold">Glendale Community College</h3><p className="mt-4 leading-8 text-muted-foreground">GCC's main campus is at 6000 W. Olive Ave. and serves Glendale and the Northwest Phoenix metro area. GCC offers more than 200 degree and certificate programs and also operates a North Campus in northwest Phoenix.</p></CardContent></Card><Card className="rounded-3xl"><CardContent className="p-8"><GraduationCap className="h-12 w-12 text-orange-500" /><h3 className="mt-6 text-2xl font-bold">ASU West Valley</h3><p className="mt-4 leading-8 text-muted-foreground">Arizona State University's West Valley campus is at 4701 W. Thunderbird Road in Glendale. The campus offers more than 125 undergraduate and graduate degree programs, including business, engineering, education, health, nursing, public service and interdisciplinary programs.</p></CardContent></Card></div></div></section>

      <section className="bg-stone-50 py-24"><div className="mx-auto max-w-6xl px-6"><div className="grid gap-14 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.35em] text-orange-500">FAMILY ENTERTAINMENT</p><h2 className="mt-4 text-4xl font-bold md:text-5xl">Glendale Keeps Adding Things To Do</h2><p className="mt-7 text-lg leading-8 text-muted-foreground">Mattel Adventure Park is planned as an indoor/outdoor family attraction featuring Mattel-themed rides and experiences. Because the project has experienced changes and delays, prospective visitors should check the official park for current opening information.</p><p className="mt-6 text-lg leading-8 text-muted-foreground">Established attractions include Andretti Indoor Karting &amp; Games, Westgate events and live music, Desert Diamond Arena and State Farm Stadium.</p></div><Card className="rounded-3xl"><CardContent className="p-8"><h3 className="text-2xl font-bold">More Glendale attractions</h3><div className="mt-6 space-y-4">{["Mattel Adventure Park — planned family attraction","Andretti Indoor Karting & Games","Westgate events and live music","Desert Diamond Arena","State Farm Stadium","Historic Downtown Glendale"].map((item) => <div key={item} className="flex gap-4"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-orange-500" /><span className="leading-7">{item}</span></div>)}</div></CardContent></Card></div></div></section>

      <section className="bg-orange-50 py-24"><div className="mx-auto max-w-6xl px-6"><div className="grid gap-14 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.35em] text-orange-500">BUYING IN GLENDALE</p><h2 className="mt-4 text-4xl font-bold md:text-5xl">Find The Location That Fits Your Lifestyle</h2><p className="mt-7 text-lg leading-8 text-muted-foreground">Whether you prioritize shopping, sports, education, recreation, entertainment or a quieter established neighborhood, Glendale gives buyers many different options.</p><p className="mt-6 text-lg leading-8 text-muted-foreground">I'll help you compare locations and properties so you understand the bigger picture before making an offer.</p></div><div className="space-y-5">{["Neighborhood and location","Home style, condition and lot","Shopping and dining","Education and community amenities","Sports, entertainment and recreation","Commute and long-term goals"].map((item) => <div key={item} className="flex items-center gap-4"><CheckCircle2 className="h-6 w-6 shrink-0 text-orange-500" /><span className="text-lg">{item}</span></div>)}</div></div></div></section>

      <section className="mx-auto max-w-7xl px-6 py-24"><div className="mx-auto max-w-4xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.35em] text-orange-500">SELLING A HOME IN GLENDALE</p><h2 className="mt-4 text-4xl font-bold md:text-5xl">Selling A Glendale Home Requires A Strategy.</h2><p className="mt-8 text-lg leading-8 text-muted-foreground">Buyers compare Glendale properties based on location, condition, features, lifestyle and value. I'll help you position your home, develop a pricing strategy, market the property, negotiate offers and manage the transaction through closing.</p><Link href="/sellers" className="mt-10 inline-block"><Button size="lg" className="px-8">Learn About Selling</Button></Link></div></section>

      <section className="bg-stone-50 py-24"><div className="mx-auto max-w-5xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.35em] text-orange-500">GLENDALE REALTOR FAQ</p><h2 className="mt-4 text-4xl font-bold md:text-5xl">Questions About Glendale Real Estate</h2></div><div className="mt-14 space-y-5">{faqs.map((faq) => <Card key={faq.question} className="rounded-2xl"><CardContent className="p-7"><h3 className="text-xl font-bold">{faq.question}</h3><p className="mt-3 leading-8 text-muted-foreground">{faq.answer}</p></CardContent></Card>)}</div></div></section>

      <section className="bg-stone-900 py-24 text-white"><div className="mx-auto max-w-3xl px-6 text-center"><Home className="mx-auto h-12 w-12 text-orange-400" /><h2 className="mt-8 text-5xl font-bold">Ready To Explore Glendale?</h2><p className="mt-8 text-xl leading-9 text-stone-300">Search available homes or contact me and let's talk about what you're looking for.</p><div className="mt-12 flex flex-wrap justify-center gap-4"><Link href="/buyers"><Button size="lg" className="px-8">Search Glendale Homes</Button></Link><Link href="/contact"><Button size="lg" variant="outline" className="border-white bg-transparent px-8 text-white hover:bg-white hover:text-stone-900">Contact Me</Button></Link></div></div></section>
    </main>
  );
}
